apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - port: 8082
    name: demo-app
    nodePort: 32426
  selector:
    app: demo-app